#!/bin/bash

if { [[ $1 == "" ]] || [[ $1 != "cheetah" && $1 != "panther" && $1 != "pantah" && $1 != "bluejay" ]]; }; then
	echo "Fuck!"
	exit 2
fi

orig=$1
tg=$1

# rename target to common target
if [[ $tg == "cheetah" || $tg == "panther" ]]; then
	tg="pantah"
fi

# build kernel
cd kernel
BUILD_KERNEL=1 ./build_$tg.sh  --kernel_package=@//aosp --config=no_download_gki --config=use_source_tree_aosp --config=release --lto=full "${@:2}"
cd .. # god damn it gh

exit 0
