name: triggered kernel build
on:
    schedule:
        - cron: '0 0 * * 1'
    workflow_dispatch:
jobs:
    bluejay:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] vy"
                git config --global user.email "vy@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-bluejay-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
            
            - name: bluejay 90hz patch
              run: |
                cp bluejay_90hz.patch ~
                cd ~
                cp bluejay_90hz.patch kernel/private/devices/google/bluejay
                git -C "kernel/private/devices/google/bluejay" apply bluejay_90hz.patch

            
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript bluejay
            
            - name: build gki with ksu
              run: |
                cd ~
                cd kernel/aosp
                curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
                rm android/abi_gki_protected_exports_*
                cd ..
                BUILD_TYPE=gki-ksu ./buildscript bluejay
            
            - name: build gki with ksu and susfs
              run: |
                cd ~
                cd kernel
                git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
                cd susfs4ksu
                cp ./kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ../aosp/KernelSU
                cp ./kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ../aosp/
                cp ./kernel_patches/fs/* ../aosp/fs/
                cp ./kernel_patches/include/linux/* ../aosp/include/linux/
                cd ../aosp/KernelSU
                patch -p1 < 10_enable_susfs_for_ksu.patch
                cd ..
                patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
                BUILD_TYPE=gki-ksu-susfs ./buildscript bluejay
            
    cheetah:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |     
                cd ~    
                git config --global user.name "[kernel buildbot] nhi"
                git config --global user.email "nhi@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-pantah-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
            
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript cheetah
            
            - name: build gki with ksu
              run: |
                cd ~
                cd kernel/aosp
                curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
                rm android/abi_gki_protected_exports_*
                cd ..
                BUILD_TYPE=gki-ksu ./buildscript cheetah
            
            - name: build gki with ksu and susfs
              run: |
                cd ~
                cd kernel
                git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
                cd susfs4ksu
                cp ./kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ../aosp/KernelSU
                cp ./kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ../aosp/
                cp ./kernel_patches/fs/* ../aosp/fs/
                cp ./kernel_patches/include/linux/* ../aosp/include/linux/
                cd ../aosp/KernelSU
                patch -p1 < 10_enable_susfs_for_ksu.patch
                cd ..
                patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
                BUILD_TYPE=gki-ksu-susfs ./buildscript cheetah    
