name: triggered kernel build
on:
    schedule:
      - cron: '0 0 * * 1'
    workflow_dispatch:
jobs:
    bluejay_gki:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] vy"
                git config --global user.email "vy@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-bluejay-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
            
            - name: checkout android14-6.1-lts
              run: |
                cd ~/kernel
                rm -rf aosp/
                git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp
  
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript bluejay

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: bluejay_gki
                 path: |
                    ~/kernel/out/bluejay/dist/*

            - name: upload to branch
              run: |
                git checkout prebuilt_bluejay_gki
                rm -rf *
                cp -rf ~/kernel/out/bluejay/dist .
                git add -A
                git commit -m '[kernel buildbot] tvy: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_bluejay_gki

    bluejay_gki-ksunext:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] vy"
                git config --global user.email "vy@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-bluejay-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync

            - name: checkout android14-6.1-lts
              run: |
                cd ~/kernel
                rm -rf aosp/
                git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp

            - name: build gki with kernelsu-next
              run: |
                cd ~
                cd kernel/aosp
                curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
                rm android/abi_gki_protected_exports_*
                cd ~
                BUILD_TYPE=gki-ksunext ./kernel/buildscript bluejay

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: bluejay_gki-ksunext
                 path: |
                    ~/kernel/out/bluejay/dist/*

            - name: upload to branch
              run: |
                git checkout prebuilt_bluejay_gki-ksunext
                rm -rf *
                cp -rf ~/kernel/out/bluejay/dist .
                git add -A
                git commit -m '[kernel buildbot] tvy: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_bluejay_gki-ksunext
    
    pantah_gki:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] nhi"
                git config --global user.email "nhi@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-pantah-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync

            - name: checkout android14-6.1-lts
              run: |
                cd ~/kernel
                rm -rf aosp/
                git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp
  
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript pantah

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: pantah_gki
                 path: |
                    ~/kernel/out/pantah/dist/*
              
            - name: upload to branch
              run: |
                git checkout prebuilt_pantah_gki
                rm -rf *
                cp -rf ~/kernel/out/pantah/dist .
                git add -A
                git commit -m '[kernel buildbot] tnhi: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_pantah_gki
          
    pantah_gki-ksunext:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] nhi"
                git config --global user.email "nhi@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-pantah-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync

            - name: checkout android14-6.1-lts
              run: |
                cd ~/kernel
                rm -rf aosp/
                git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp

            - name: build gki with kernelsu-next
              run: |
                cd ~
                cd kernel/aosp
                curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -
                rm android/abi_gki_protected_exports_*
                cd ~
                BUILD_TYPE=gki-ksunext ./kernel/buildscript pantah

            - name: upload build artifacts
              uses: actions/upload-artifact@v4
              with:
                 name: pantah_gki-ksunext
                 path: |
                    ~/kernel/out/pantah/dist/*

            - name: upload to branch
              run: |
                git checkout prebuilt_pantah_gki-ksunext
                rm -rf *
                cp -rf ~/kernel/out/pantah/dist .
                git add -A
                git commit -m '[kernel buildbot] tnhi: upload prebuilt to branch' --signoff
                git push -u origin prebuilt_pantah_gki-ksunext
