name: g201 kernel build
on:
  workflow_dispatch:
    inputs:
      kernel_variant:
        description: 'Kernel variant to build'
        required: true
        type: choice
        default: gki-ksunext
        options:
          - gki
          - gki-ksunext

jobs:
  build_kernel:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout scripts
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: install packages
        run: |
          ./pkginstall

      - name: init credentials
        run: |   
          cd ~      
          git config --global user.name "[kernel buildbot] vy"
          git config --global user.email "vy@buildbot.tvyiutnhisokewt"
      
      - name: checkout aosp kernel build system
        run: |
          cp buildscript ~ 
          cd ~        
          mkdir kernel
          cp buildscript kernel
          cd kernel
          repo init -u https://github.com/EduardoA3677/android-gs-pantah-6.1-android15-qpr2 --depth 1
          repo sync -c -j6 --no-tags --no-clone-bundle --force-sync

      - name: checkout android14-6.1-lts
        run: |
          cd ~/kernel
          rm -rf aosp/
          git clone https://android.googlesource.com/kernel/common -b android14-6.1-lts --depth=1 aosp
          
      # KSU specific steps
      - name: clone wild kernel patches + susfs4ksu
        if: github.event.inputs.kernel_variant == 'gki-ksunext' || contains(github.ref, 'gki_ksu')
        run: |
          git clone https://github.com/WildPlusKernel/kernel_patches.git
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
          mv kernel_patches ~/kernel
          mv susfs4ksu ~/kernel

      - name: patch kernel ksunext susfs
        if: github.event.inputs.kernel_variant == 'gki-ksunext' || contains(github.ref, 'gki_ksu')
        run: |
          cd ~
          cd kernel/aosp
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs
          git submodule update --init --recursive
          cd KernelSU-Next/kernel
          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" Makefile
          cd ..
          cd ..
          rm android/abi_gki_protected_exports_*
          cd ~/kernel
          cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./aosp/
          cp susfs4ksu/kernel_patches/fs/* ./aosp/fs/
          cp susfs4ksu/kernel_patches/include/linux/* ./aosp/include/linux/
          #cp kernel_patches/next/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./aosp/KernelSU-Next
          cd ~/kernel/aosp
          patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
          cd ~/kernel/aosp/KernelSU-Next
          #patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
          cd ..
          cp ../kernel_patches/next/syscall64_hooks.patch ./ 
          cp ../kernel_patches/69_hide_stuff.patch ./ 
          patch -p1 -F 3 < syscall64_hooks.patch
          patch -p1 -F 3 < 69_hide_stuff.patch
          cd ~/kernel
          echo "Adding configuration settings to gki_defconfig..."
          # Add KSU configuration settings
          echo "CONFIG_KSU=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_WITH_KPROBES=n" >> ./aosp/arch/arm64/configs/gki_defconfig
          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./aosp/arch/arm64/configs/gki_defconfig
          # Add additional tmpfs config setting
          echo "CONFIG_TMPFS_XATTR=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          # Add additional config setting
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_COMPAT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_VFS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
  
          sed -i 's/CONFIG_LTO=n/CONFIG_LTO=y/' "./aosp/arch/arm64/configs/gki_defconfig"
          sed -i 's/CONFIG_LTO_CLANG_FULL=y/CONFIG_LTO_CLANG_THIN=y/' "./aosp/arch/arm64/configs/gki_defconfig"
          sed -i 's/CONFIG_LTO_CLANG_NONE=y/CONFIG_LTO_CLANG_THIN=y/' "./aosp/arch/arm64/configs/gki_defconfig"
          

          sed -i 's/check_defconfig//' ./aosp/build.config.gki
          cd ~/kernel
          sed -i 's/-dirty//' ./aosp/scripts/setlocalversion
          perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./aosp/scripts/mkcompile_h
          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
          
      - name: build kernel
        run: |
          cd ~
          BUILD_TYPE=${{ github.event.inputs.kernel_variant || 'gki' }} ./kernel/buildscript

      - name: Buscar defconfig del kernel
        continue-on-error: true
        run: |
          cd ~/kernel/aosp
          mkdir -p output

          # Buscar y copiar los archivos deseados
          find . -type f \( \
            -name ".config" -o \
            -name "*.config" -o \
            -name "*defconfig" -o \
            -name "*_defconfig" -o \
            -name "gs201_defconfig" -o \
            -name "*Kconfig.ext.gs201" -o \
            -name "*gs201" -o \
            -name "gs201*" -o \
            -name "*gs201*" -o \
            -name "*.tar.gz" -o \
            -name "*.gz" -o \
            -name "*.zip" \
          \) -exec cp --parents {} output/ \;

          # Comprimir los resultados en un .zip
          cd output
          zip -r "../kernel_configs.zip" ./*
          
      - name: Subir artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: kernel-configs-${{ github.event.inputs.kernel_variant || 'gki' }}
          path: ~/kernel/aosp/kernel_configs.zip
          
      - name: Buscar y comprimir archivos de configuración del kernel
        continue-on-error: true
        run: |
          cd ~/kernel/out
          mkdir -p output

          # Buscar y copiar los archivos deseados
          find . -type f \( \
            -name ".config" -o \
            -name "*.config" -o \
            -name "*defconfig" -o \
            -name "*.tar.gz" -o \
            -name "*.zip" \
          \) -exec cp --parents {} output/ \;

          # Comprimir los resultados en un .zip
          cd output
          zip -r "../kernel_files.zip" ./*
          
      - name: Subir artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: kernel-files-${{ github.event.inputs.kernel_variant || 'gki' }}
          path: ~/kernel/out/kernel_files.zip
          
      - name: Pack AnyKernel3
        continue-on-error: true
        run: |
          cd ~/kernel
          git clone -b gs201 --recursive --depth=1 -j $(nproc) https://github.com/EduardoA3677/AnyKernel3.git AnyKernel3
          cp ~/kernel/out/gs201/dist/Image.lz4 ~/kernel/AnyKernel3/Image.lz4
          cat ~/kernel/out/gs201/dist/*.dtb > ~/kernel/AnyKernel3/dtb
          cp ~/kernel/out/gs201/dist/dtbo.img ~/kernel/AnyKernel3/dtbo.img
          cp ~/kernel/out/gs201/dist/vendor_kernel_boot.img ~/kernel/AnyKernel3/vendor_kernel_boot.img
          cd ~/kernel/AnyKernel3
          zip -r "../GS201_A15_GKI_6.1_Next_SUSFS.zip" ./*

      - name: Pack kernel build imgs output
        continue-on-error: true
        run: |
          cd ~/kernel/out/gs201/dist
          mkdir imgs
          cp *.img imgs
          cd imgs
          zip -r "imgs.zip" ./*

      - name: Pack dist output
        continue-on-error: true
        run: |
          cd ~/kernel/out/gs201/dist
          zip -r "dist.zip" ./*

      - name: upload dist zip as artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: kernel-out-${{ github.event.inputs.kernel_variant || 'gki' }}
          path: ~/kernel/out/gs201/dist/dist.zip
          
      - name: upload images build zip as artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: kernel-imgs-${{ github.event.inputs.kernel_variant || 'gki' }}
          path: ~/kernel/out/gs201/dist/imgs/imgs.zip
          
      - name: upload AnyKernel3 zip as artifact
        continue-on-error: true
        uses: actions/upload-artifact@v4
        with:
          name: kernel-dist-${{ github.event.inputs.kernel_variant || 'gki' }}
          path: ~/kernel/GS201_A15_GKI_6.1_Next_SUSFS.zip
