name: triggered kernel build
on:
    push:
        branches:
            - gki
            - gki_ksu
            - gki_ksu_susfs
            - sauce
    workflow_dispatch:
jobs:
    bluejay:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |   
                cd ~      
                git config --global user.name "[kernel buildbot] vy"
                git config --global user.email "vy@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-bluejay-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
            
            - name: bluejay 90hz patch
              run: |
                cd ~
                rm -rf kernel/private/devices/google/bluejay/*
                git clone https://github.com/tvyiutnhisokewt/private_devices_google_bluejay
                cp -r private_devices_google_bluejay/* kernel/private/devices/google/bluejay/

            
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript bluejay
            
            - name: build gki with ksu
              run: |
                cd ~
                cd kernel/aosp
                curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
                rm android/abi_gki_protected_exports_*
                cd ~
                BUILD_TYPE=gki-ksunext ./kernel/buildscript bluejay
            
            - name: build gki with ksu and susfs
              run: |
                cd ~
                cd kernel
                git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
                cd susfs4ksu
                cp ./kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ../aosp/KernelSU
                cp ./kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ../aosp/
                cp ./kernel_patches/fs/* ../aosp/fs/
                cp ./kernel_patches/include/linux/* ../aosp/include/linux/
                cd ../aosp/KernelSU
                patch -p1 < 10_enable_susfs_for_ksu.patch
                cd ..
                patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
                cd ~
                BUILD_TYPE=gki-ksunext-susfs ./kernel/buildscript bluejay
            
    cheetah:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout scripts
              uses: actions/checkout@v4
            
            - name: install packages
              run: |
                ./pkginstall

            - name: init credentials
              run: |     
                cd ~    
                git config --global user.name "[kernel buildbot] nhi"
                git config --global user.email "nhi@buildbot.tvyiutnhisokewt"
            
            - name: checkout aosp kernel build system
              run: |
                cp buildscript ~ 
                cd ~
                mkdir kernel
                cp buildscript kernel
                cd kernel
                repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-pantah-6.1-android15-qpr2-beta --depth 1
                repo sync -c -j$(nproc --all) --no-tags --no-clone-bundle --force-sync
            
            - name: build gki
              run: |
                cd ~
                BUILD_TYPE=gki ./kernel/buildscript cheetah
            
            - name: build gki with ksu
              run: |
                cd ~
                cd kernel/aosp
                curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
                rm android/abi_gki_protected_exports_*
                cd ~
                BUILD_TYPE=gki-ksunext ./kernel/buildscript bluejay
            
            - name: build gki with ksu and susfs
              run: |
                cd ~
                cd kernel
                git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
                cd susfs4ksu
                cp ./kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ../aosp/KernelSU
                cp ./kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ../aosp/
                cp ./kernel_patches/fs/* ../aosp/fs/
                cp ./kernel_patches/include/linux/* ../aosp/include/linux/
                cd ../aosp/KernelSU
                patch -p1 < 10_enable_susfs_for_ksu.patch
                cd ..
                patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
                cd ~
                BUILD_TYPE=gki-ksunext-susfs ./kernel/buildscript bluejay 
