name: triggered kernel build
on:
  workflow_dispatch:
    inputs:
      kernel_variant:
        description: 'Kernel variant to build'
        required: true
        type: choice
        default: gki-ksunext
        options:
          - gki
          - gki-ksunext

jobs:
  build_kernel:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout scripts
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: install packages
        run: |
          ./pkginstall

      - name: init credentials
        run: |   
          cd ~      
          git config --global user.name "[kernel buildbot] vy"
          git config --global user.email "vy@buildbot.tvyiutnhisokewt"
      
      - name: checkout aosp kernel build system
        run: |
          cp buildscript ~ 
          cd ~        
          mkdir kernel
          cp buildscript kernel
          cd kernel
          repo init -u https://android.googlesource.com/kernel/manifest.git -b android-gs-pantah-6.1-android15-qpr2-beta --depth 1
          repo sync -c -j6 --no-tags --no-clone-bundle --force-sync

      # KSU specific steps
      - name: clone wild kernel patches + susfs4ksu
        if: github.event.inputs.kernel_variant == 'gki-ksunext' || contains(github.ref, 'gki_ksu')
        run: |
          git clone https://github.com/WildPlusKernel/kernel_patches.git
          git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
          mv kernel_patches ~/kernel
          mv susfs4ksu ~/kernel

      - name: patch kernel ksunext susfs
        if: github.event.inputs.kernel_variant == 'gki-ksunext' || contains(github.ref, 'gki_ksu')
        run: |
          cd ~
          cd kernel/aosp
          curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs
          git submodule update --init --recursive
          cd KernelSU-Next/kernel
          KSU_VERSION=$(expr $(/usr/bin/git rev-list --count HEAD) "+" 10200)
          echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
          sed -i "s/DKSU_VERSION=11998/DKSU_VERSION=${KSU_VERSION}/" Makefile
          cd ..
          cd ..
          rm android/abi_gki_protected_exports_*
          cd ~/kernel
          cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./aosp/
          cp susfs4ksu/kernel_patches/fs/* ./aosp/fs/
          cp susfs4ksu/kernel_patches/include/linux/* ./aosp/include/linux/
          #cp kernel_patches/next/0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch ./aosp/KernelSU-Next
          cd ~/kernel/aosp
          patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
          cd ~/kernel/aosp/KernelSU-Next
          #patch -p1 --forward < 0001-kernel-patch-susfs-v1.5.5-to-KernelSU-Next-v1.0.5.patch || true
          cd ..
          cp ../kernel_patches/next/syscall_hooks.patch ./ 
          cp ../kernel_patches/69_hide_stuff.patch ./ 
          patch -p1 -F 3 < syscall_hooks.patch
          patch -p1 -F 3 < 69_hide_stuff.patch
          cd ~/kernel
          echo "Adding configuration settings to gki_defconfig..."
          # Add KSU configuration settings
          echo "CONFIG_KSU=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_WITH_KPROBES=n" >> ./aosp/arch/arm64/configs/gki_defconfig
          # Add SUSFS configuration settings
          echo "CONFIG_KSU_SUSFS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> ./aosp/arch/arm64/configs/gki_defconfig
          # Add additional tmpfs config setting
          echo "CONFIG_TMPFS_XATTR=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          # Add additional config setting
          echo "CONFIG_IP_NF_TARGET_TTL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_TARGET_HL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_IP6_NF_MATCH_HL=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_ADVANCED=y" >> ./aosp/arch/arm64/configs/gki_defconfig 
          echo "CONFIG_TCP_CONG_BBR=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_NET_SCH_FQ=y" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_BIC=n" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_WESTWOOD=n" >> ./aosp/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TCP_CONG_HTCP=n" >> ./aosp/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./aosp/build.config.gki
          cd ~/kernel
          sed -i '$s|echo "\$res"|echo "\$res-eduardo"|' ./aosp/scripts/setlocalversion
          perl -pi -e 's{UTS_VERSION="\$\(echo \$UTS_VERSION \$CONFIG_FLAGS \$TIMESTAMP \| cut -b -\$UTS_LEN\)"}{UTS_VERSION="#1 SMP PREEMPT Sat Apr 20 04:20:00 UTC 2024"}' ./aosp/scripts/mkcompile_h
          sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl
          sed -E -i '/^CONFIG_LOCALVERSION=/ s/(.*)"$/\1-eduardo"/' ./aosp/arch/arm64/configs/gki_defconfig
          
      - name: build kernel
        run: |
          cd ~
          BUILD_TYPE=${{ github.event.inputs.kernel_variant || 'gki' }} ./kernel/buildscript pantah

      - name: Pack AnyKernel3
        run: |
          cd ~/kernel
          git clone --recursive --depth=1 -j $(nproc) https://github.com/EduardoA3677/AnyKernel3.git AnyKernel3
          cp ~/kernel/out/pantah/dist/Image.lz4 ~/kernel/AnyKernel3/Image.lz4
          cat ~/kernel/out/pantah/dist/*.dtb > ~/kernel/AnyKernel3/dtb
          cp ~/kernel/out/pantah/dist/dtbo.img ~/kernel/AnyKernel3/dtbo.img
          cd ~/kernel/AnyKernel3
          zip -r "../GS201_A15_GKI_6.1_Next_SUSFS.zip" ./*

      - name: Pack kernel build imgs output
        run: |
          cd ~/kernel/out/pantah/dist
          mkdir imgs
          cp *.img imgs
          cd imgs
          zip -r "imgs.zip" ./*
                
      - name: Pack all output
        run: |
          cd ~/kernel/out
          zip -r "out.zip" ./*
          
      - name: upload all out zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-out-${{ github.event.inputs.kernel_variant || 'gki' }}
          path: ~/kernel/out/out.zip

      - name: upload images build zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-imgs-${{ github.event.inputs.kernel_variant || 'gki' }}
          path: ~/kernel/out/pantah/dist/imgs/imgs.zip
          
      - name: upload AnyKernel3 zip as artifact
        uses: actions/upload-artifact@v4
        with:
          name: kernel-dist-${{ github.event.inputs.kernel_variant || 'gki' }}
          path: ~/kernel/GS201_A15_GKI_6.1_Next_SUSFS.zip
